config/routes.rb
Rails.application.routes.draw do

  resources :home, only: [:index]

  resources :users, only: [:new, :create, :show]

  post '/project_member/manager' => 'project_assignments#add_manager', as: :add_manager

  post '/project_member/not_manager' => 'project_assignments#remove_manager', as: :remove_manager

  get '/project_member/search' => 'project_assignments#search_member', as: :search_member

  get '/project/map' => 'projects#map', as: :project_map

  resources :projects, except: [:index] do
    resources :sprints
    resources :snippets
    resources :mudas
  end

  post '/project/complete' => 'projects#complete', as: :project_complete
  post '/project/cancel' => 'projects#cancel', as: :project_cancel

  post '/tasks/complete' => 'tasks#complete', as: :task_complete

  resources :sprints, only: [] do
    resources :user_stories, except: [:index, :show]
    resources :tasks, except: [:show]
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :planning_highlights, only: [:index, :new, :create, :destroy]
    resources :review_highlights, only: [:index, :new, :create, :destroy]
  end

    # get '/sprints/:sprint_id/tasks/tree' => 'tasks#tree_data', as: :task_tree

  resources :project_assignments, only: [:new, :create, :destroy]
  resources :task_assignments, only: [:create, :destroy]

  resources :my_projects, only: [:index]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]


  root "home#index"

end

app/models/review_highlight.rb
class ReviewHighlight < ActiveRecord::Base
  belongs_to :sprint

  validates :description, presence: true
end

app/controllers/review_highlights_controller.rb
class ReviewHighlightsController < ApplicationController
  before_action :authenticate_user
  before_action :find_review_highlight, only: [:destroy]
  before_action :find_sprint, only: [:index, :new, :create, :destroy]

  # before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @review_highlights = @sprint.review_highlights
    @review_highlight = ReviewHighlight.new
  end

  def new
    @review_highlight = ReviewHighlight.new
    respond_to do |format|
      format.js  { render :new}
    end
  end

  def create
    @review_highlight = ReviewHighlight.new review_highlight_params
    @review_highlight.sprint = @sprint
    if @review_highlight.save
      redirect_to sprint_review_highlights_path(@sprint), notice: "Highlight created!"
    else
      redirect_to sprint_review_highlights_path(@sprint), alert: "Error happened: Highlight could not be created."
    end
  end

  def destroy
    find_review_highlight.destroy
    redirect_to sprint_review_highlights_path(@sprint), notice: "Highlight deleted!"
  end

  private

  def review_highlight_params
    params.require(:review_highlight).permit(:description)
  end

  def find_review_highlight
    @review_highlight = ReviewHighlight.find params[:id]
  end

  def find_sprint
    @sprint = Sprint.find params[:sprint_id]
  end

  # def authorize_user
  #   unless can? :manage, @review_highlight
  #     redirect_to root_path, alert: "access denied!"
  #   end
  # end

end

app/helpers/review_highlights_helper.rb
module ReviewHighlightsHelper
end

app/views/review_highlights/_form.html.erb
<%= simple_form_for [@sprint, @review_highlight] do |f| %>

    <%= f.input :description, label: false %>
    <%= f.submit %>

  <% end %>

app/views/review_highlights/index.html.erb
<p>
  <%= link_to fa_icon('chevron-left', text: "Sprint"), project_sprint_path(@sprint.project, @sprint), class: "btn btn-link" %>
</p>

<%= @review_highlight.errors.full_messages.join(", ") %>

<h3>Planning Meeting Highlights</h3>

<p>
  <%= link_to "new", new_sprint_review_highlight_path(@sprint), remote: true, class: "btn btn-default" %>
</p>

<div id='review_highlight-form'>

</div>

<br>

<table class="table table-striped">
  <% @review_highlights.each do |plan| %>
  <tr>
    <td><em><%= plan.id %></em></td>
    <div class="">
      <td><%= raw sanitize plan.description.gsub("\n", "<br />"), tags: %w(br) %></td>

    </div>
    <td>
      <%= link_to fa_icon("trash"), sprint_review_highlight_path(@sprint, plan),
                            method: :delete,
                            data: {confirm: "Delete this highlight?"}%>
  </tr>
  <% end %>
</table>

app/views/review_highlights/new.js.erb
$("#review_highlight-form").html("<%= j render 'form'%>")