config/routes.rb
Rails.application.routes.draw do

  resources :home, only: [:index]

  resources :users, only: [:new, :create, :show]

  post '/project_member/manager' => 'project_assignments#add_manager', as: :add_manager

  post '/project_member/not_manager' => 'project_assignments#remove_manager', as: :remove_manager

  get '/project_member/search' => 'project_assignments#search_member', as: :search_member

  get '/project/map' => 'projects#map', as: :project_map

  resources :projects, except: [:index] do
    resources :sprints
    resources :snippets
    resources :mudas
  end

  post '/project/complete' => 'projects#complete', as: :project_complete
  post '/project/cancel' => 'projects#cancel', as: :project_cancel

  post '/tasks/complete' => 'tasks#complete', as: :task_complete

  resources :sprints, only: [] do
    resources :user_stories, except: [:index, :show]
    resources :tasks, except: [:show]
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :planning_highlights, only: [:index, :new, :create, :destroy]
    resources :review_highlights, only: [:index, :new, :create, :destroy]
  end

    # get '/sprints/:sprint_id/tasks/tree' => 'tasks#tree_data', as: :task_tree

  resources :project_assignments, only: [:new, :create, :destroy]
  resources :task_assignments, only: [:create, :destroy]

  resources :my_projects, only: [:index]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]


  root "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  include AASM

  belongs_to :sprint
  belongs_to :node,     class_name: "Task", foreign_key: "task_id"
  has_many   :children, class_name: "Task", foreign_key: "task_id"
  has_many :task_assignments, dependent: :destroy
  has_many :users, through: :task_assignments

  validates :title, presence: true

  aasm whiny_transitions: false do
    state :created, initial: true
    state :in_progress
    state :complete

    event :start do
      transitions from: :created, to: :in_progress
    end

    event :finish do
      transitions from: [:in_progress, :created], to: :complete
    end

    event :go_back do
      transitions from: :in_progress, to: :created
    end

  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user
  before_action :find_sprint, except: [:complete]
  before_action :find_task, only: [:edit, :update, :destroy, :complete]
  before_action :authorize_management, except: [:complete]

  def new
    @task  = Task.new
    @tasks = @sprint.tasks
    respond_to do |format|
      format.js { render :new }
    end
  end

  # will render the task tree
  def index
    @tasks = @sprint.tasks
    respond_to do |format|
      format.html { render }
      format.json { render }
    end
  end


  def create
    @task   = Task.new task_params
    @task.sprint = @sprint
    respond_to do |format|
      if @task.save
        format.js { render :create_success }
      else
        format.js { render :create_fail }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js { render :edit }
    end
  end

  def update
    respond_to do |format|
      if @task.update task_params
        format.js   { render :update_success }
      else
        format.js   { render :update_fail }
      end
    end
  end

  def destroy
    @task.destroy
    redirect_to project_sprint_path(@sprint.project, @sprint)
  end

  def complete
    @sprint = @task.sprint
    @task.finish!
    respond_to do |format|
      format.html { redirect_to sprint_tasks_path(@sprint) }
      format.js   { render }
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :task_id)
  end

  def find_task
    @task = Task.find params[:id]
  end

  def find_sprint
  @sprint = Sprint.find params[:sprint_id]
  end

  def authorize_management
    unless can? :manage, @sprint.project
      redirect_to root_path, alert: "access denied!"
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for [@sprint, @task], remote: true do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.association :node, collection: @sprint.tasks, label: "Dependence", prompt: "Select a dependence, if any" %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id(task) %>">
  <div class="task-details">
    <h3><%= task.title %></h3>
    <div>
      <%= raw sanitize task.description.gsub("\n", "<br />"), tags: %w(br) %>
<%= task.aasm_state %>

      <div class="">
        <% task.users.each do |user|%>
          <%= fa_icon("user") %> <%=  user.full_name %>
        <% end %>
      </div>

      <p>

        <% if task.aasm_state != "complete"  %>
          <% if task.users.exists?(current_user)%>
          <%= link_to "Leave", task_assignment_path(task), method: :delete, remote: true, class: "btn btn-link overdue" %>
          <% else %>
          <%= link_to "Pick", task_assignments_path(task_id: task), method: :post, remote: true, class: "btn btn-link complete" %>
          <% end %>
          <p>
            <%= link_to "Task is complete!", task_complete_path(id: task.id, sprint_id: task.sprint), method: :post, class: "btn complete", remote: true %>
          </p>
        <% end %>
      </p>

      <%= link_to fa_icon("edit"), edit_sprint_task_path(task.sprint, task), remote: true %>
      <%= link_to fa_icon("trash"),
      sprint_task_path(task.sprint, task),
      method: :delete,
      data: {confirm: "Are you sure you want to delete this task? This action cannot be undone"} %>
    </div>
  </div>
</div>

app/views/tasks/complete.js.erb
$("#<%= dom_id(@task) %>").replaceWith("<%= j render 'tasks/task', task: @task %>");
$( ".accordion" ).accordion( "refresh" );
$( ".accordion" ).accordion({
  active: false
});

app/views/tasks/create_fail.js.erb
$("#task-form").html("<%= j render 'form' %>");

app/views/tasks/create_success.js.erb
$('.tasks').append("<%= j render 'task', task: @task %>");
$( ".accordion" ).accordion( "refresh" );

$("#task-form").hide();
$("#new-task-link").show();

app/views/tasks/edit.js.erb
$("#<%= dom_id(@task) %> .task-details").html("<%= j render 'form'%>")

app/views/tasks/index.html.erb
<%= link_to fa_icon('chevron-left', text: "Sprint"), project_sprint_path(@sprint.project, @sprint), class: "btn btn-link" %>

<div >
  <h3><%= @sprint.title %></h3>
</div>

  <div id="chart"></div>

  <div id="sprint-id" style="display: none">
    <%= @sprint.id %>
  </div>



<%= javascript_include_tag "tree/tree" %>

<!-- Modal -->
<div class="modal fade" id="taskModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-task-title">Modal title</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to "Leave", task_assignment_path(0), method: :delete, class: "btn btn-link overdue", id: "modal-leave" %>
        <%= link_to "Pick", task_assignments_path(task_id: 0), method: :post, class: "btn btn-link complete", id: "modal-pick" %>
        <%= link_to "Task is complete!", task_complete_path(id: 0), method: :post, class: "btn complete", id: "modal-complete"%>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.js.erb
$("#new-task-link").hide();
$("#task-form").html("<%= j render 'form' %>").show();

app/views/tasks/update_fail.js.erb
document.location.reload(true);

app/views/tasks/update_success.js.erb
document.location.reload(true);