config/routes.rb
Rails.application.routes.draw do

  resources :home, only: [:index]

  resources :users, only: [:new, :create, :show]

  post '/project_member/manager' => 'project_assignments#add_manager', as: :add_manager

  post '/project_member/not_manager' => 'project_assignments#remove_manager', as: :remove_manager

  get '/project_member/search' => 'project_assignments#search_member', as: :search_member

  get '/project/map' => 'projects#map', as: :project_map

  resources :projects, except: [:index] do
    resources :sprints
    resources :snippets
    resources :mudas
  end

  post '/project/complete' => 'projects#complete', as: :project_complete
  post '/project/cancel' => 'projects#cancel', as: :project_cancel

  post '/tasks/complete' => 'tasks#complete', as: :task_complete

  resources :sprints, only: [] do
    resources :user_stories, except: [:index, :show]
    resources :tasks, except: [:show]
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :planning_highlights, only: [:index, :new, :create, :destroy]
    resources :review_highlights, only: [:index, :new, :create, :destroy]
  end

    # get '/sprints/:sprint_id/tasks/tree' => 'tasks#tree_data', as: :task_tree

  resources :project_assignments, only: [:new, :create, :destroy]
  resources :task_assignments, only: [:create, :destroy]

  resources :my_projects, only: [:index]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]


  root "home#index"

end

app/models/muda.rb
class Muda < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :title,       presence: true
  validates :description, presence: true

#test this method
  def self.filter_project(project)
    where("project_id = ?", project.id)
  end

end

app/controllers/mudas_controller.rb
class MudasController < ApplicationController
  before_action :authenticate_user
  before_action :find_project
  before_action :find_muda, only: [:show, :edit, :update, :destroy]


  def index
    @mudas =  Muda.filter_project(@project).order("created_at DESC")
  end

  def new
    @muda = Muda.new
  end

  def create
    @muda = Muda.new muda_params
    @muda.user = current_user
    @muda.project = @project
    if @muda.save
      redirect_to project_muda_path(@project, @muda), notice: "Muda created"
    else
      flash[:alert] = "Error: Muda was not created"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @muda.update muda_params
      redirect_to project_muda_path(@project, @muda), notice: "Muda Updated!"
    else
      flash[:alert] = "Error: Muda was not updated!"
      render :edit
    end
  end

  def destroy
    if current_user == @muda.user
      @muda.destroy
    end
    redirect_to project_mudas_path(@project)
  end

  # def user_mudas
  #   @user_mudas = current_user.mudas
  #   render :user_mudas
  # end
  #
  #
  private

  def muda_params
    params.require(:muda).permit(:title, :description)
  end

  def find_project
    @project = Project.find_by_id params[:project_id]
  end

  def find_muda
    @muda = Muda.find  params[:id]
  end
end

app/helpers/mudas_helper.rb
module MudasHelper
end

app/views/mudas/_form.html.erb
<%= @muda.errors.full_messages.join(", ") %>

<%= simple_form_for [@project, @muda] do |f| %>
  <%= f.input :title %>
  <%= f.input :description, label: "Work", input_html: { rows: 10 }%>
  <%= f.submit %>
<% end %>

app/views/mudas/edit.html.erb
<h1>Edit Muda</h1>

<%= render "form" %>

app/views/mudas/index.html.erb
<p>
  <%= link_to fa_icon('chevron-left', text: "Project"), project_path(@project), class: "btn btn-link" %>
</p>

<h2>Mudas for the project "<%= @project.title %>"</h2>

<%= link_to "New Muda", new_project_muda_path(@project), class: "btn btn-default" %>

<% @mudas.each do |muda| %>
  <div class="well">
    <%= link_to muda.title, project_muda_path(@project, muda) %>
  </div>
<% end %>

app/views/mudas/new.html.erb
<h2>Create a muda</h2>
You can use markdown and indicate code mudas with
<br>
```[language]
<br>
```
<%= render "form" %>

app/views/mudas/show.html.erb
<p>
  <%= link_to fa_icon('chevron-left', text: "All Muda"), project_mudas_path(@project), class: "btn btn-link" %>
</p>

<h1><%= @muda.title %></h1>
<% if current_user == @muda.user %>
<%= link_to fa_icon("edit"), edit_project_muda_path(@project, @muda) %>
<%= link_to fa_icon("trash"),
project_muda_path(@project, @muda),
method: :delete,
data: {confirm: "Are you sure you want to delete this muda? This action cannot be undone"} %>
<% end %>
<p><em>Created by: <%= @muda.user.full_name %></em></p>

<%= markdown(@muda.description )%>