config/routes.rb
Rails.application.routes.draw do

  resources :home, only: [:index]

  resources :users, only: [:new, :create, :show]

  post '/project_member/manager' => 'project_assignments#add_manager', as: :add_manager

  post '/project_member/not_manager' => 'project_assignments#remove_manager', as: :remove_manager

  get '/project_member/search' => 'project_assignments#search_member', as: :search_member

  get '/project/map' => 'projects#map', as: :project_map

  resources :projects, except: [:index] do
    resources :sprints
    resources :snippets
    resources :mudas
  end

  post '/project/complete' => 'projects#complete', as: :project_complete
  post '/project/cancel' => 'projects#cancel', as: :project_cancel

  post '/tasks/complete' => 'tasks#complete', as: :task_complete

  resources :sprints, only: [] do
    resources :user_stories, except: [:index, :show]
    resources :tasks, except: [:show]
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :planning_highlights, only: [:index, :new, :create, :destroy]
    resources :review_highlights, only: [:index, :new, :create, :destroy]
  end

    # get '/sprints/:sprint_id/tasks/tree' => 'tasks#tree_data', as: :task_tree

  resources :project_assignments, only: [:new, :create, :destroy]
  resources :task_assignments, only: [:create, :destroy]

  resources :my_projects, only: [:index]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]


  root "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  include AASM

  belongs_to :creator, class_name: "User", foreign_key: 'user_id'
  has_many :project_assignments, dependent: :destroy
  has_many :members, through: :project_assignments, source: :user
  has_many :sprints,  dependent: :destroy
  has_many :snippets, dependent: :destroy
  has_many :mudas,    dependent: :destroy

  validates :title, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  aasm whiny_transitions: false do
    state :draft, initial: true
    state :in_progress
    state :complete
    state :overdue
    state :cancelled

    event :start do
      transitions from: :draft, to: :in_progress
    end

    event :finish do
      transitions from: :in_progress, to: :complete
    end

    event :expire do
      transitions from: :in_progress, to: :overdue
    end

    event :cancel do
      transitions from: [:draft, :in_progress], to: :cancelled
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user
  before_action :find_project, only: [:show, :edit, :update, :destroy, :cancel, :complete, :map]
  before_action :authorize_management, only: [:edit, :update, :destroy, :cancel, :complete]


  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    @project.creator = current_user
    if @project.save
      current_user.projects << @project
      schedule_background_job
      redirect_to project_path(@project), notice: "New Project Created!"
    else
      flash[:alert] = "Project could not be created."
      render :new
    end
  end

  def show
    if @project
      @sprint = Sprint.new
      @sprints = @project.sprints.order(created_at: :desc)
      render :show
    else
      redirect_to root_path, alert: "Project Not Found"
    end
  end

  def edit
    respond_to do |format|
      format.js { render :edit }
    end
  end

  def update
    respond_to do |format|
      if @project.update project_params
        format.js   { render :update_success }
        schedule_background_job
      else
        format.js   { render :update_fail }
      end
    end
  end

  def destroy
    @project.destroy
    redirect_to my_projects_path
  end

  def complete
    @project.finish!
    @project.actual_end_date = Date.today
    @project.save
    redirect_to my_projects_path
  end

  def cancel
    @project.cancel!
    redirect_to my_projects_path
  end

  def map
    respond_to do |format|
      format.html { render }
      format.json { render }
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :start_date, :end_date)
  end

  def find_project
    @project = current_user.projects.find_by_id params[:id]
  end

  def authorize_management
    unless can? :manage, @project
      redirect_to root_path, alert: "access denied!"
    end
  end

  def schedule_background_job
    DetermineProjectStateJob.perform_now(@project)
    DetermineProjectStateJob.set(wait_until: @project.start_date).perform_later(@project)
    DetermineProjectStateJob.set(wait_until: @project.end_date).perform_later(@project)
    true
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for @project, remote: @project.persisted? do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :start_date, as: :date_time_picker %>
  <%= f.input :end_date, as: :date_time_picker %>
  <%= f.submit %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#project_end_date, #project_start_date').datepicker({ dateFormat: 'dd/mm/yy' });
  });
</script>

app/views/projects/_project.html.erb
<div class="project-details">
  <% if can? :manage, @project %>
  <%= link_to fa_icon("edit"), edit_project_path(@project), remote: true %>
  <%= link_to fa_icon("trash"),
  project_path(@project),
  method: :delete,
  data: {confirm: "Are you sure you want to delete this project? This action cannot be undone"} %>
  <% end %>
  <em>
    <p >Creator: <%= @project.creator.full_name%></p>
    <p>Starts on: <%= @project.start_date.strftime("%d/%b/%Y") %> | Ends on: <%= @project.end_date.strftime("%d/%b/%Y") %></p>

  </em>
  <p><%= @project.description %></p>
  <h4> Members:</h4>
  <!-- add user -->
  <p>
    <%= link_to fa_icon("user-plus"), new_project_assignment_path(project_id: @project), remote: true %>
  </p>

  <!-- search -->
  <div id="search-member-form"></div>
  <div id="search-member-result"></div>
  <!-- end  of search -->
  <!-- end of add user -->
  <p>
    <% @project.members.each do |member| %>
    <div class="member col-md-4 col-sm-6 col-xm-12">
      <h4><%= member.full_name %></h4>

      <% if can? :manage, @project %>
      <%= link_to "Remove",
      project_assignment_path(project_id: @project, user_id: member),
      method: :delete, class: "btn btn-link overdue",
      data: {confirm: "Are you sure you want to remove this team member?"} %>
      <% if member.is_manager?(@project) %>
      <%=  link_to "Manager", remove_manager_path(project_id: @project, user_id: member), method: :post, class: "btn btn-link complete", 'data-toggle' => 'tooltip', :title => 'Remove manager'%>
      <% else %>
      <%=  link_to "Set as Manager", add_manager_path(project_id: @project, user_id: member), method: :post, :class => "btn btn-link", 'data-toggle' => 'tooltip', :title => 'Set as manager'%>
      <% end %>
      <% end %>
    </div>
    <% end %>
  </p>

  <br>



</div>

app/views/projects/edit.js.erb
$("#<%= dom_id(@project) %> .project-details").fadeOut(1000).remove();
$("#<%= dom_id(@project) %>").prepend("<%= j render 'form'%>")

app/views/projects/map.html.erb
 <div class="container">
   <%= link_to fa_icon('chevron-left', text: "Project"), project_path(@project), class: "btn btn-link" %>
   <div >
     <h3><%= @project.title %></h3>
   </div>
   <div id="project-id" style="display: none">
     <%= @project.id %>
   </div>


   <script>
   var projectId = $("#project-id").html()

   var diameter = 800,
   format = d3.format(",d");

   var pack = d3.layout.pack()
   .size([diameter - 4, diameter - 4])
   .value(function(d) { return d.size; });

   var svg = d3.select("body").append("svg")
   .attr("width", diameter)
   .attr("height", diameter)
   .append("g")
   .attr("transform", "translate(2,2)");

   d3.json("/project/map.json?id=" + projectId, function(error, root) {
     if (error) throw error;

     var node = svg.datum(root).selectAll(".node")
     .data(pack.nodes)
     .enter().append("g")
     .attr("class", function(d) { return d.status ; })
     .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });

     node.append("title")
     .text(function(d) { return d.name ; });

     node.append("circle")
     .attr("r", function(d) { return d.r; });

     node.filter(function(d) { return !d.children; }).append("text")
     .attr("dy", ".3em")
     .style("text-anchor", "middle")
     .text(function(d) { return d.name.substring(0, d.r / 3); });
   });


   d3.select(self.frameElement).style("height", diameter + "px");

   </script>
 </div>

app/views/projects/new.html.erb
<%= render "form"%>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<div class="container">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">Details</a></li>
    <li><a data-toggle="tab" href="#menu1">Sprints</a></li>
    <li><a data-toggle="tab" href="#menu2">Resources</a></li>
    <li><a data-toggle="tab" href="#menu3">Actions</a></li>
  </ul>

  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <br>
      <h3>Details</h3>
        <%= link_to fa_icon("area-chart", text: "Project Map"), project_map_path(id: @project), class: "btn btn-default"%>

      <div id="<%= dom_id(@project) %>">
        <%= render 'project' %>
      </div>
    </div>

    <!-- sprints menu  -->
    <div id="menu1" class="tab-pane fade">
      <br>
      <h3>Sprints</h3>

      <div id="new-sprint-link">
        <%= link_to "New Sprint", new_project_sprint_path(@project),
        remote: true, class: "btn btn-default" %>
      </div>
      <br>
      <br>
      <div class="sprints">
        <% @sprints.each do |s| %>
        <%= render "/sprints/sprint_link", sprint: s %>
        <% end %>
      </div>

      <div id="sprint-form"></div>
    </div>
    <!-- end of sprints  -->

    <!-- resources menu  -->
    <div id="menu2" class="tab-pane fade">
      <br>
      <h3>Resources</h3>
      <p>
        <%= link_to "Snippets", project_snippets_path(@project), class: "btn btn-default" %>
      </p>
      <p>
        <%= link_to fa_icon("bug", text: "Muda"), project_mudas_path(@project), class: "btn btn-default btn-resources" %>
      </p>
    </div>
    <!-- end of resources  -->

    <!-- actions menu  -->
    <div id="menu3" class="tab-pane fade">
      <br>
      <h3>Actions</h3>
      <p>
        <%= link_to "Project is complete!", project_complete_path(id: @project.id), method: :post, class: "btn complete" %>
      </p>
      <p>
        <%= link_to "Cancel project", project_cancel_path(id: @project.id), method: :post, class: "btn cancelled" %>
      </p>
    </div>
    <!-- end of actions  -->
  </div>
</div>

app/views/projects/update.fail.js.erb
$("#<%= dom_id(@project) %>").html("<%= j render 'project'%>");

app/views/projects/update_success.js.erb
$("#<%= dom_id(@project) %>").html("<%= j render 'project' %>");